#!/usr/bin/env bash
# Make the webserver listens to port 80.
sudo apt-get purge nginx nginx-common
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx restart
