#!/usr/bin/env bash
#make your web server listen to port 80 while nginx is not running
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill nginx
