#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.
# cant be killed with SIGTERM
trap "echo 'I am invincible!!!'" SIGTERM
while [ 1 ]
do
    echo To infinity and beyond
    sleep 2
done
