#!/usr/bin/env bash
# Bash script that displays H... S... 10 times, at 9th iteration display "Hi"

i=0
while [ $i -lt 10 ]
do
    echo Holberton School
    if [ $i -eq 8 ]
    then
	echo Hi
    fi
    (( i++ ))
done
