#!/usr/bin/env bash
# Bash script that displays the time for 12h and 59m

i=0
while [ $i -lt 13 ]
do
    echo Hour: $i
    j=1
    while [ $j -lt 60 ]
    do
	echo $j
	(( j++ ))
    done
    (( i++ ))
done
