#!/usr/bin/env bash
# make nginx run as nginx user
# nginx must be listening on all active IPs on port 8080
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/" /etc/nginx/sites-available/default
echo "user nginx;" >> /etc/nginx/nginx.conf
sudo service nginx restart
