#!/usr/bin/env bash
# make nginx run as nginx user
# nginx must be listening on all active IPs on port 8080
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/g" /etc/nginx/sites-available/default
sudo service nginx restart
ubuntu config --default-user nginx
